[env]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
# Paramètres flash/mémoire pour exploiter pleinement le S3
board_build.arduino.memory_type = qio_opi 
board_build.f_flash = 80000000L
board_build.flash_mode = qio
lib_deps = 
    zinggjm/GxEPD2 @ ^1.6.7
    jgromes/RadioLib @ ^6.6.0
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit BusIO @ ^1.15.0
    knolleary/PubSubClient @ ^2.8
    sandeepmistry/LoRa @ ^0.8.0

[env:postit_device]
build_flags = 
    -D MODE_POSTIT
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:gateway_device]
build_flags = 
    -D MODE_GATEWAY
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1